### ISSUE TITLE
Failed to build gem native extension, using x86_64-darwin-20 extension

### ISSUE THREAD

**Issue by hopewise** [cotag/http-parser#18]
I am trying to install the gem using Mac Pro intel:
```
gem install http-parser -v '1.2.3' --source 'https://rubygems.org/' 
``` 

but I am getting error:

```
ERROR:  Error installing http-parser:
        ERROR: Failed to build gem native extension.

    current directory: /Users/user/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/http-parser-1.2.3/ext
/Users/user/.asdf/installs/ruby/2.3.0/bin/ruby -rubygems /Users/user/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/rake-13.0.6/exe/rake RUBYARCHDIR=/Users/user/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-20/2.3.0-static/http-parser-1.2.3 RUBYLIBDIR=/Users/user/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-20/2.3.0-static/http-parser-1.2.3
/Users/user/.asdf/installs/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require': cannot load such file -- rake (LoadError)
        from /Users/user/.asdf/installs/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from /Users/user/.asdf/installs/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from /Users/user/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/rake-13.0.6/exe/rake:25:in `<main>'

rake failed, exit code 1

Gem files will remain installed in /Users/user/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/gems/http-parser-1.2.3 for inspection.
Results logged to /Users/user/.asdf/installs/ruby/2.3.0/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-20/2.3.0-static/http-parser-1.2.3/gem_make.out
```

I tried to:

```
time bundle lock --add-platform x86_64-linux --add-platform ruby
bundle install
```

but that hasn't solved the issue

**Comment by StefanTheWiz** [comment]
see https://github.com/cotag/http-parser/issues/17
